### ISSUE TITLE
Error on startup - PopupMenu not found

### ISSUE THREAD

**Issue by skewty** [TheoThePerson/GnomeLama#5]
Fedora Linux 40 (Workstation Edition) Gnome 46

Is that library an additional install?  I did a `dnf search popup` and didn't see anything that looked like a good match.

![image](https://github.com/user-attachments/assets/2d9534ff-e553-499a-bc67-3d255ff914ef)

I am guessing it is this line:
https://github.com/TheoThePerson/GnomeLama/blob/fa0fe1684cb25f53f136fb45c38126a2abad2aed/extension.js#L1

**Comment by TheoThePerson** [comment]
This project is far from completion and doesn't even work yet this is something somebody else put in and I have not had the time yet to make it work when winter break comes around I should have more time to work on it and actually make it functional. I am running debain 12 and I am also getting that error. The person who made that code was able to run it on fedora 40 though. If you have experience with making gnome extensions I would appreciate the help.

**Comment by skewty** [comment]
I have a bit. I will try to find some time this weekend to take a look.

**Comment by TheoThePerson** [comment]
Cool, thanks, I have very limited experience with making gnome extensions and working with java script. I am focusing my attention on my schooling and a online java script course. It would be great to have some help on this project!
